#!/usr/bin/env bash

#ensure this is the directory you extracted to
INSTALL_DIR=~/bin


LIB_DIR="$INSTALL_DIR/gs-avro-tools-lib"
LOCAL_SCHEMA_REPO="$INSTALL_DIR/gs-avro-tools-schemas"

REMOTE_SCHEMA_REPO="gs://fq-platform/artifacts/releases/fq/platform/data-common"
REMOTE_RELEASES="gs://miral/tools/avro/releases"

JAR_FILE=gs-avro-tools-assembly-latest.jar
JAR_PATH="$LIB_DIR/$JAR_FILE"

update_repo () {
  mkdir -p ${LOCAL_SCHEMA_REPO}
  gsutil -m rsync -x ".*sources.*|.*pom|.*md5|.*sha1|.*xml" -r ${REMOTE_SCHEMA_REPO} ${LOCAL_SCHEMA_REPO}
}

get_latest_jar () {
  mkdir -p ${LIB_DIR}
  gsutil cp "$REMOTE_RELEASES/$JAR_FILE" ${JAR_PATH}
}

if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
  java -jar $JAR_PATH -h
elif [ "$1" == "update" ]; then #update before first use
  update_repo
elif [ "$1" == "upgrade" ]; then #copy latest jar from remote
  get_latest_jar
elif [ "$1" == "install" ]; then
  get_latest_jar
  update_repo
else
  java -jar ${JAR_PATH} --localrepo ${LOCAL_SCHEMA_REPO} "$@"
fi
