#!/usr/bin/env bash

#ensure this is the directory you extracted to
GS_UTIL_AVRO_DIR=~/bin
LOCAL_REPO="$GS_UTIL_AVRO_DIR/gs-avro-tools-schemas"
REMOTE_REPO="gs://fq-platform/artifacts/releases/fq/platform/data-common"


JAR="$GS_UTIL_AVRO_DIR/gs-avro-tools-lib/gs-avro-tools-assembly-0.2.jar"
if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
  java -jar $JAR -h
elif [ "$1" == "update" ]; then #update before first use
  mkdir -p $LOCAL_REPO
  gsutil -m rsync -x ".*sources.*|.*pom|.*md5|.*sha1|.*xml" -r $REMOTE_REPO $LOCAL_REPO
else
  java -jar $JAR --localrepo $LOCAL_REPO "$@"
fi